---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: labeler-role-binding
subjects:
  - kind: ServiceAccount
    name: clusterops
roleRef:
  kind: Role
  name: auto-labeler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: labeler-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: clusterops
    namespace: labeler
roleRef:
  kind: ClusterRole
  name: auto-labeler-cluster-role
  apiGroup: rbac.authorization.k8s.io
