---
apiVersion: v1
kind: Service
metadata:
  name: label-controller-metrics
  namespace: labeler
  labels:
    app: label-controller
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: label-controller

