/*
Copyright 2025 Abhishek Ghosh

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisclusteropsv1alpha1 "github.com/ab-ghosh/knative-controller/pkg/apis/clusterops/v1alpha1"
	versioned "github.com/ab-ghosh/knative-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ab-ghosh/knative-controller/pkg/client/informers/externalversions/internalinterfaces"
	clusteropsv1alpha1 "github.com/ab-ghosh/knative-controller/pkg/client/listers/clusterops/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// LabelerInformer provides access to a shared informer and lister for
// Labelers.
type LabelerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() clusteropsv1alpha1.LabelerLister
}

type labelerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewLabelerInformer constructs a new informer for Labeler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewLabelerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredLabelerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredLabelerInformer constructs a new informer for Labeler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredLabelerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusteropsV1alpha1().Labelers(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusteropsV1alpha1().Labelers(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusteropsV1alpha1().Labelers(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusteropsV1alpha1().Labelers(namespace).Watch(ctx, options)
			},
		},
		&apisclusteropsv1alpha1.Labeler{},
		resyncPeriod,
		indexers,
	)
}

func (f *labelerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredLabelerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *labelerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisclusteropsv1alpha1.Labeler{}, f.defaultInformer)
}

func (f *labelerInformer) Lister() clusteropsv1alpha1.LabelerLister {
	return clusteropsv1alpha1.NewLabelerLister(f.Informer().GetIndexer())
}
